repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: format
        name: format
        entry: uv run ruff format .
        language: system
        pass_filenames: false
        files: "^(pympo|tests)"

      - id: fix-lint
        name: fix-lint
        entry: uv run ruff check --fix .
        language: system
        pass_filenames: false
        files: "^(pympo|tests)"

      - id: typecheck
        name: mypy
        entry: uv run mypy --install-types --non-interactive pympo
        language: system
        pass_filenames: false
        files: "^(pympo/|)"

      - id: pytest
        name: pytest
        entry: cd tests/build && uv run pytest -n auto ..
        language: system
        pass_filenames: false
        files: "^(pympo/|tests/)"
