line-length = 80
target-version = "py312"
#extend-exclude = ["*.ipynb"]
#extend-include = ["*.ipynb"]

[lint]
select = [
  # list of rules are available at https://beta.ruff.rs/docs/rules/
  "E",  # pycodestyle (error)
  "W",  # pycodestyle (warning)
  "F",  # Pyflakes
  "B",  # flake8-bugbear
  "I",  # isort
]
ignore = [
  "B018", # useless-expression
  "E501", # line too long
  "E731", # do not assign a lambda expression, use a def
]

[lint.pydocstyle]
convention = "google"
